### ISSUE TITLE
No interactive pointers

### ISSUE THREAD

**Issue by Rishav13773** [sudeepmahato16/movie-app#1]
I noticed a issue that none of the interactive div element elements have pointer cursor when we hover or click on it.
also i want to change the default look of the cursor to go more with theme of the app

**SOMETHING LIKE THIS :**

![pack349](https://github.com/sudeepmahato16/movie-app/assets/98654904/6400f23e-55ee-4055-af21-b91c95dca82e)

**Comment by sudeepmahato16** [comment]
I've looked into the interactive div elements, and it seems that none of them currently have a default cursor applied. Could you please show me the interactive div elements that have a default cursor?

**Comment by Rishav13773** [comment]
@sudeepmahato16 Well its strange, now the pointed cursor is showing, tho I cannot find any css property which define it explicitly. And before it was default cursor for every div which are interactive. Nevertheless I think there is a issue from my end.
But I still wish to add a custom cursor.

**Comment by sudeepmahato16** [comment]
If you wish to add the custom cursor yourself, go ahead. 👍
